# Generated by Django 3.2 on 2021-04-18 22:56

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
