# Generated by Django 3.2 on 2021-07-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210422_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='identifier',
        ),
    ]
